#!/usr/bin/env python3
"""Generate deterministic demand corpora for languages the GitHub Typo
Corpus does not cover (plan 09 / corpus plan 107).

The bucket export (scripts/export_buckets.py) derives its DEMAND set and
its gate probes from eval/corpora/{lang}.json - real human typo pairs.
The GitHub Typo Corpus covers only 9 of our languages (fetch_corpus.py
LANG_MAP); the remaining model languages have no real typo corpus at all.
For those, this script writes eval/corpora/{lang}.synth.json in the same
shape: (typo, correct, count) pairs generated by the repo's own
deterministic keyboard-aware typo model (eval/noise.py - the same
generator the tier eval gates use for every language) over the most
frequent mini-tier vocabulary words.

The pairs are a deployment proxy, not human data; the corpus metadata
says so, and the per-language buckets report (eval/reports/{lang}
.buckets.json) records probe counts honestly. Determinism: the generator
seed is [42, crc32("<lang>:synth")], so a regenerated corpus is
byte-identical.

Usage:
    python3 scripts/synth_corpus.py --repo-root . [--lang fr,...]
"""

from __future__ import annotations

import argparse
import json
import sys
import zlib
from collections import Counter
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "eval"))
from noise import make_typo  # noqa: E402

# Languages with a real GitHub-corpus file ({lang}.json) are excluded;
# everything else the registry serves that noise.py can corrupt gets a
# synthetic corpus. ja/ko/zh ride their real corpora; en/de already
# shipped buckets in v1.4.0.
SYNTH_LANGS = (
    "ar", "bg", "br", "ca", "cs", "cy", "da", "el", "eo", "et", "eu", "fa",
    "fy", "ga", "gd", "gl", "he", "hr", "hu", "hy", "ia", "id", "is",
    "it", "ka", "la", "lb", "lt", "lv", "mk", "mn", "nb", "ne", "nl",
    "nn", "oc", "pl", "ro", "sk", "sl", "sr", "sv", "tk", "tr", "uk",
    "vi",
)

# Demand/gate probe budget of the exporter: DEMAND_PAIRS=2000 top pairs
# form the demand set, probes come from the pairs ranked below them.
# 9000 candidates leave ~6000 surviving pairs: 2000 demand + 3200 gate
# pool + margin, so the gate probes stay disjoint from the demand set.
N_WORDS = 9000


def synth_pairs(lang: str, vocab: dict) -> list[list]:
    rng = np.random.default_rng([42, zlib.crc32(f"{lang}:synth".encode("utf-8"))])
    words = sorted(vocab, key=vocab.get)
    pairs: list[list] = []
    seen: Counter = Counter()
    for rank, word in enumerate(words):
        if len(pairs) >= N_WORDS:
            break
        w = word.lower()
        if not (3 <= len(w) <= 24) or any(ch.isspace() for ch in w) or not w.isalpha():
            continue
        typo = make_typo(rng, w, lang)
        if typo is None or typo == w or typo in vocab:
            continue
        seen[(typo, w)] += 1
        # Count monotone in frequency rank: the demand weighting and the
        # gate-probe sampling of the exporter follow corpus counts, so
        # frequent words' typos drive the keep set, as in a real corpus.
        pairs.append([typo, w, max(1, N_WORDS - rank)])
    dedup = []
    for typo, w, count in pairs:
        if seen[(typo, w)] == 1:
            dedup.append([typo, w, count])
    return dedup


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo-root", default=".")
    ap.add_argument("--lang", help="comma-separated subset of SYNTH_LANGS")
    args = ap.parse_args()

    root = Path(args.repo_root).resolve()
    langs = args.lang.split(",") if args.lang else list(SYNTH_LANGS)
    corpora_dir = root / "eval" / "corpora"
    corpora_dir.mkdir(parents=True, exist_ok=True)

    for lang in langs:
        if lang not in SYNTH_LANGS:
            print(f"skip {lang}: not a synthetic-corpus language (has a real corpus?)", file=sys.stderr)
            continue
        vocab_path = root / "models" / lang / f"fasttext.{lang}.mini.vocab.json"
        vocab = json.loads(vocab_path.read_text(encoding="utf-8"))["word_to_idx"]
        pairs = synth_pairs(lang, vocab)
        if len(pairs) < 400:
            print(f"error: {lang}: only {len(pairs)} pairs - too few to gate on", file=sys.stderr)
            return 1
        out = {
            "language": lang,
            "corpus": {
                "name": "synthetic keyboard-noise corpus",
                "version": "1.0.0",
                "generator": "scripts/synth_corpus.py (eval/noise.py typo model)",
                "seed": 42,
                "deterministic": True,
                "note": ("proxy demand corpus - the GitHub Typo Corpus has no "
                         "coverage for this language; pairs are noise.py typos "
                         "over the top mini-tier vocabulary, frequency-weighted"),
            },
            "extraction": {
                "rule": "one noise.py typo per frequent vocab word (3..24 alpha chars), OOV typos only",
                "deduplicated": True,
            },
            "n_pairs_unique": len(pairs),
            "pairs": pairs,
        }
        path = corpora_dir / f"{lang}.synth.json"
        path.write_text(json.dumps(out, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"{lang}: {len(pairs)} pairs -> {path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
